- name: Install Packages
  ansible.builtin.apt:
    name:
      - build-essential      
      - pip
      - gradle
      - golang
      - golang-go    
      - ruby-full
      - git
      - npm
      - maven
